M48
; DRILL file KiCad 10.0.4 date 2026-08-11T10:40:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-11T10:40:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X149.795Y-93.37
X149.795Y-99.15
T2
X167.09Y-97.835
X172.17Y-96.819
X172.17Y-98.851
M30
